version: '1.0'

services:
  minio :
      image: minio/minio
      ports:
          - 9000:9000
          - 9001:9001
      volumes:
          - ./volumes/minio:/data
      environment:
          MINIO_ROOT_USER: admin
          MINIO_ROOT_PASSWORD: 123456789
      command: server --console-address ":9001" /data
      restart: always

